# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: c2c7b6f15adbff0eb7b9b38a7b30c9fe2ed96c0b440a431cab4c06092ee19b27aa39f37824d59660b7af00f4b57fc228f4b4586d9a98b61f7e8d78b2c88bb4f0

test:
  secret_key_base: b3f8b68157b4914e681004c7e5a7b36f18be3776bd0c770051b72268cb03d567ec72198f911d2742d224fc39a3b0e4ba3311cc4fdc55aec4c57acff3dd6d75a6

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
